// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slvjvjwrkesjfzxcygdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsdmp2andya2VzamZ6eGN5Z2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTk0NTIsImV4cCI6MjA3MTYzNTQ1Mn0.wz2dDrmu8yZCWxHmbxERmQzBa6Ll8e35YlYlQfGo7Nc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});